--Display all flights with:
---Flight Number
--Flight Date
--Ticket Price
--Sort by the highest ticket price.

SELECT 
	FlightNumber,
	FlightDate,
	TicketPrice
FROM Flights
ORDER BY TicketPrice DESC

--Show each aircraft model and the number of flights it has operated.
SELECT
	a.AircraftModel,
	COUNT(f.FlightID) AS Total_flights
FROM Aircraft AS a
JOIN Flights AS f
	ON a.AircraftID=f.AircraftID
GROUP BY
	a.AircraftModel


--Calculate the total revenue generated by each aircraft.
SELECT 
	a.AircraftModel,
	SUM(f.TicketPrice * f.Passengers) AS total_revenue
FROM Aircraft  AS a
JOIN Flights AS f
	ON a.AircraftID=f.AircraftID
GROUP BY
	a.AircraftModel

--Find all airports that have handled more than two departures
SELECT 
	f.DepartureAirportID,
	a.AirportName,
	COUNT(f.FlightID) AS no_Of_flights
FROM Flights AS f
JOIN Airports AS a
	ON f.DepartureAirportID=a.AirportID
GROUP BY 
	f.DepartureAirportID,
	a.AirportName
HAVING
	COUNT(FlightID)>2

--Which route generated the highest total revenue?
SELECT TOP 1
    f.DepartureAirportID,
    f.ArrivalAirportID,
    a.AirportName AS DepartureAirport,
    d.AirportName AS ArrivalAirport,
    SUM(f.TicketPrice * f.Passengers) AS TotalRevenue
FROM Flights AS f
JOIN Airports AS a
    ON f.DepartureAirportID = a.AirportID
JOIN Airports AS d
    ON f.ArrivalAirportID = d.AirportID
GROUP BY
    f.DepartureAirportID,
    f.ArrivalAirportID,
    a.AirportName,
    d.AirportName
ORDER BY
    TotalRevenue DESC